import fs from "node:fs/promises";
import path from "node:path";
import { pinyin } from "pinyin";
import { CHARACTER_RECOGNITION_BANK } from "../src/routes/characterRecognitionBank";

async function main() {
  const values = CHARACTER_RECOGNITION_BANK.map((character) => {
    const value = pinyin(character, { style: "tone" }).flat()[0];
    if (!value) throw new Error(`缺少拼音：${character}`);
    return value;
  });
  const rows = [];
  for (let index = 0; index < values.length; index += 16) {
    rows.push(`  ${values.slice(index, index + 16).map((value) => JSON.stringify(value)).join(", ")}`);
  }
  const output = [
    "// Generated by backend/scripts/generate-flash-test-character-pinyin.ts.",
    "const { CHARACTER_BANK } = require(\"./characterRecognitionBank\");",
    "",
    "const CHARACTER_PINYIN = [",
    rows.join(",\n"),
    "];",
    "",
    "if (CHARACTER_PINYIN.length !== CHARACTER_BANK.length) throw new Error(\"识字量拼音表长度无效\");",
    "",
    "const CHARACTER_PINYIN_BY_CHARACTER = Object.fromEntries(",
    "  CHARACTER_BANK.map((character, index) => [character, CHARACTER_PINYIN[index]])",
    ");",
    "",
    "function getCharacterPinyin(character) {",
    "  return CHARACTER_PINYIN_BY_CHARACTER[String(character || \"\")] || \"\";",
    "}",
    "",
    "module.exports = { CHARACTER_PINYIN, getCharacterPinyin };",
    ""
  ].join("\n");
  const target = path.resolve(
    __dirname,
    "../../apps/wechat-miniprogram/utils/characterRecognitionPinyin.js"
  );
  await fs.writeFile(target, output);
  console.log(`generated ${values.length} pinyin entries`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
